FROM centos
LABEL maintainer="leitao.zhang@phpstu.com"

ENV PATH $PATH:/usr/local/bin
#拷贝文件
COPY file_tar/ /usr/local/src/

RUN echo 'export LC_ALL=C' >> ~/.bashrc && source ~/.bashrc && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 && yum -y install epel-release && yum -y update && yum install -y /usr/bin/applydeltarpm  wget gcc gcc-c++ ncurses ncurses-devel bison libgcrypt perl automake autoconf libtool make  libxml2 libxml2-devel libjpeg libjpeg-devel libpng libpng-devel freetype freetype-devel zlib zlib-devel glibc glibc-devel glib2 glib2-devel curl curl-devel php-mcrypt libmcrypt libmcrypt-devel openssl-devel gd mcrypt mhash libicu-devel && yum clean all

#COPY FILES 
RUN cd /usr/local/src/nginx-files && ls | xargs -n1 tar xzvf && cd /usr/local/src/php-files && ls | xargs -n1 tar xzvf && mkdir -p /var/nginx && mkdir -p /var/www &&  mkdir -p /tmp/nginx_logs 
# ADD USER
RUN groupadd www && useradd -r -g www www 

#INSTALL NGINX 
RUN cd /usr/local/src/nginx-files/nginx-1.10.3 && ./configure --prefix=/usr/local/nginx --user=www --group=www --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module --with-ipv6 --with-poll_module --with-select_module --with-pcre=/usr/local/src/nginx-files/pcre-8.40 --with-zlib=/usr/local/src/nginx-files/zlib-1.2.11 --with-openssl=/usr/local/src/nginx-files/openssl-1.1.0e && make && make install 
RUN ln -s /usr/local/nginx/sbin/nginx /usr/local/bin/nginx
RUN cd && rm -rf /usr/local/src/nginx-files/nginx-1.10.3
RUN \cp -f  /usr/local/src/config/nginx.conf /usr/local/nginx/conf

# INSTALL PHPINIT
RUN mv /usr/local/src/phpunit-5.7.27.phar /usr/local/bin/phpunit && chmod +x /usr/local/bin/phpunit


#INSTALL PHP5.6
RUN cd /usr/local/src/php-files/php-5.6.36 && ./configure  --prefix=/usr/local/php56 --enable-fpm --enable-pcntl --with-mysql=mysqlnd --with-mcrypt --enable-bcmath --with-curl --with-gd --enable-gd-native-ttf --with-freetype-dir --enable-intl --with-mysql-sock=/tmp/mysqld.sock --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-libxml-dir=/usr/lib64 --with-mhash --enable-sockets --with-png-dir=/usr/lib64 --with-jpeg-dir=/usr/lib64 --with-zlib --enable-opcache --enable-zip --enable-mbstring --with-openssl --with-pcre-regex && make && make install 
RUN cd && rm -rf /usr/local/src/php-files/php-5.6.36

# CONFIG PHP5.6  
RUN ln -s /usr/local/php56/bin/php /usr/local/bin/php  && ln -s /usr/local/php56/sbin/php-fpm /usr/local/bin/php-fpm  && ln -s /usr/local/php56/bin/php-config /usr/bin/php-config

RUN \cp -f /usr/local/src/config/php.ini /usr/local/php56/lib
RUN \cp -f /usr/local/src/config/php-fpm.conf /usr/local/php56/etc

#==== PHP5.6 === EXTENSION
# PHP5.6 INSTALL REDIS 
RUN cd /usr/local/src/php-files/redis-4.2.0 && /usr/local/php56/bin/phpize && ./configure --with-php-config=/usr/bin/php-config && make && make install && cd && rm -rf /usr/local/src/php-files/redis-4.2.0   
# PHP5.6 INSTALL LIBMEMCACHED
RUN cd /usr/local/src/php-files/libmemcached-1.0.18 && ./configure && make && make install 
# PHP5.6 install memcached
RUN cd /usr/local/src/php-files/memcached-2.2.0  && /usr/local/php56/bin/phpize && ./configure --with-php-config=/usr/bin/php-config --disable-memcached-sasl && make && make install  && cd && rm -rf /usr/local/src/php-files/memcached-2.2.0
# PHP5.6 install memcache
RUN cd /usr/local/src/php-files/memcache-2.2.7 && /usr/local/php56/bin/phpize && ./configure --with-php-config=/usr/bin/php-config && make && make install && cd && rm -rf /usr/local/src/php-files/memcache-2.2.7
# PHP5.6 install APCU
RUN cd /usr/local/src/php-files/apcu-4.0.10 && /usr/local/php56/bin/phpize && ./configure --with-php-config=/usr/bin/php-config && make && make install && cd  && rm -rf /usr/local/src/php-files/apcu-4.0.10

#+======7.1======
# install 7.1
RUN cd /usr/local/src/php-files/php-7.1.18 && ./configure  --prefix=/usr/local/php71 --enable-fpm --enable-pcntl --with-mcrypt --enable-bcmath --with-curl --with-gd --enable-gd-native-ttf --with-freetype-dir --enable-intl --with-mysql-sock=/tmp/mysqld.sock --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-libxml-dir=/usr/lib64 --with-mhash --enable-sockets --with-png-dir=/usr/lib64 --with-jpeg-dir=/usr/lib64 --with-zlib --enable-opcache --enable-zip --enable-mbstring --with-openssl --with-pcre-regex && make && make install  && cd /usr/local/src/php-files && cd && rm -rf /usr/local/src/php-files/php-7.1.18
# php7.1 redis 
RUN cd /usr/local/src/php-files && tar zxvf /usr/local/src/php-files/redis-4.2.0.tgz && cd /usr/local/src/php-files/redis-4.2.0 && /usr/local/php71/bin/phpize && ./configure --with-php-config=/usr/local/php71/bin/php-config && make && make install && cd && rm -rf /usr/local/src/php-files/redis-4.2.0
# php7.1 memcached
RUN cd /usr/local/src/php-filesmemcached-3.1.3/  && /usr/local/php71/bin/phpize && ./configure --with-php-config=/usr/local/php71/bin/php-config --disable-memcached-sasl && make && make install && cd && rm -rf /usr/local/src/php-files/memcached-3.1.3
#php7.1 apcu
RUN cd /usr/local/src/php-files/apcu-5.1.11 && /usr/local/php71/bin/phpize && ./configure --with-php-config=/usr/local/php71/bin/php-config && make && make install && cd && rm -rf /usr/local/src/php-files/apcu-5.1.11
# LINK PHP7.1
RUN ln -s /usr/local/php71/bin/php /usr/local/bin/php71 

RUN \cp -f /usr/local/src/config/php71.ini /usr/local/php71/lib/php.ini
RUN \cp -f /usr/local/src/config/www.conf /usr/local/php71/etc/php-fpm.d/www.conf

###===========

# install 7.3 ===
# update libzip > 1.0 
RUN yum remove libzip -y
RUN cd /usr/local/src/php-files/libzip-1.2.0 && ./configure && make && make install && cd && rm -rf /usr/local/src/php-files/libzip-1.2.0

# cp cancel -i 
RUN \cp -f /usr/local/lib/libzip/include/zipconf.h /usr/local/include/zipconf.h

RUN cd /usr/local/src/php-files/php-7.3.0 && ./configure  --prefix=/usr/local/php73 --enable-fpm --enable-pcntl --enable-bcmath --with-curl --with-gd --with-freetype-dir --enable-intl --with-mysql-sock=/tmp/mysqld.sock --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-libxml-dir=/usr/lib64 --with-mhash --enable-sockets --with-png-dir=/usr/lib64 --with-jpeg-dir=/usr/lib64 --with-zlib --enable-opcache --enable-zip --enable-mbstring --with-openssl --with-pcre-regex && make && make install && cd && rm -rf /usr/local/src/php-files/php-7.3.0

RUN \cp -f /usr/local/src/config/php73.ini /usr/local/php73/lib/php.ini
RUN \cp -f /usr/local/src/config/www73.conf /usr/local/php73/etc/php-fpm.d/www.conf
RUN ln -s /usr/local/php73/bin/php /usr/local/bin/php73 

# php7.3 redis 
RUN cd /usr/local/src/php-files && tar zxvf /usr/local/src/php-files/redis-4.2.0.tgz && cd /usr/local/src/php-files/redis-4.2.0 && /usr/local/php73/bin/phpize && ./configure --with-php-config=/usr/local/php73/bin/php-config && make && make install && cd && rm -rf /usr/local/src/php-files/redis-4.2.0
# php7.3 memcached
RUN cd /usr/local/src/php-files && tar zxvf /usr/local/src/php-files/memcached-3.1.3.tgz && cd /usr/local/src/php-files/memcached-3.1.3  && /usr/local/php73/bin/phpize && ./configure --with-php-config=/usr/local/php73/bin/php-config --disable-memcached-sasl && make && make install && cd && rm -rf /usr/local/src/php-files/memcached-3.1.3
#php7.3 apcu
RUN cd /usr/local/src/php-files && tar zxvf /usr/local/src/php-files/apcu-5.1.11.tgz && cd /usr/local/src/php-files/apcu-5.1.11 && /usr/local/php73/bin/phpize && ./configure --with-php-config=/usr/local/php73/bin/php-config && make && make install && cd && rm -rf /usr/local/src/php-files/apcu-5.1.11

#REMOVE FILES
RUN rm -rf /usr/local/src/nginx-files/* && rm -rf /usr/local/src/php-files/* && rm -rf /usr/local/src/config/*

#CONFIG AUTO START
RUN echo "#!/bin/bash" > /usr/local/bin/lnmp 
RUN echo "/usr/local/bin/php-fpm" >> /usr/local/bin/lnmp 
RUN echo '/usr/local/php71/sbin/php-fpm -y /usr/local/php71/etc/php-fpm.d/www.conf' >> /usr/local/bin/lnmp
RUN echo '/usr/local/php73/sbin/php-fpm -y /usr/local/php73/etc/php-fpm.d/www.conf' >> /usr/local/bin/lnmp
RUN echo "/usr/local/bin/nginx -g 'daemon off;'" >> /usr/local/bin/lnmp && chmod +x /usr/local/bin/lnmp

CMD [ "/usr/local/bin/lnmp" ] 

EXPOSE 80 443